version: '3.8'

services:

  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - ./bsnbot.env
    environment:
      POSTGRES_DB: cryptodb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  logging:
    image: datalust/seq:2021.2
    container_name: logging
    restart: unless-stopped
    environment:
      # SEQ_FIRSTRUN_ADMINPASSWORDHASH: "$PH"
      ACCEPT_EULA: Y
    volumes:
      - type: volume
        source: app-logs
        target: /data
    ports:
      - 5341:80
    # healthcheck: # no curl in image
    #   test: ["CMD", "curl", "-f", "http://localhost:5341"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  dbupdate:
    image: bsngroup/trader:$trader_version
    container_name: dbupdate
    env_file:
      - ./bsnbot.env
    environment:
      Serilog__WriteTo__1__Args__ServerUrl: "http://logging:5341"
      STARTUP_DLL: Crypto.Database.Upgrade.dll
      Serilog__MinimumLevel: Debug
    working_dir: /app/Crypto.Database.Upgrade
    depends_on: 
      db:
        condition: service_healthy
      # logging: 
      #   condition: true
      

  trader:
    image: bsngroup/trader:$trader_version
    container_name: trader
    restart: unless-stopped
    env_file:
      - ./bsnbot.env
    environment:
      Serilog__WriteTo__1__Args__ServerUrl: "http://logging:5341"
      STARTUP_DLL: Crypto.Trader.dll
      cli_args: $trader_cli_args
    working_dir: /app/Crypto.Trader
    ports:
      - 5000:5000

  analyzer:
    image: bsngroup/analyzer:$analyzer_version
    container_name: analyzer
    restart: unless-stopped
    env_file:
      - ./bsnbot.env
    environment:
      environment: live
      
  ui:
    image: bsngroup/cryptobot-ui:latest
    container_name: ui
    restart: unless-stopped
    env_file:
      - ./bsnbot.env
    ports:
      - 5050:5000 

volumes:
  db-data:
  app-logs:

    